name: Build
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        config: [debug, release]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install system packages
        uses: ConorMacBride/install-package@v1
        with:
          apt: libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config libgl1-mesa-dev libx11-dev libxrandr-dev
          brew: pkg-config

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install dependencies
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgConfigurationJsonGlob: "vcpkg-configuration.json"

      - name: Run CMake and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "${{ matrix.os }}-${{ matrix.config }}"
          buildPreset: "${{ matrix.os }}-${{ matrix.config }}"
          packagePreset: "${{ matrix.os }}-${{ matrix.config }}"

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/v') && matrix.config == 'release'
        with:
          draft: true
          files: "out/build/${{ matrix.os }}-${{ matrix.config }}/dist/*"
          fail_on_unmatched_files: true
          generate_release_notes: true
